import React, { useState } from 'react';
import { PageTab, BlogArticle } from '../types';
import { INITIAL_BLOG_ARTICLES } from '../data/mockData';
import { 
  BookOpen, 
  Sparkles, 
  Search, 
  Clock, 
  User, 
  Tag, 
  ArrowRight, 
  X, 
  CheckCircle2, 
  Loader2, 
  Share2, 
  TrendingUp, 
  Zap, 
  Plus,
  RefreshCw
} from 'lucide-react';

interface BlogPageProps {
  setActiveTab: (tab: PageTab) => void;
  selectedArticleId?: string | null;
  onSelectArticle?: (id: string | null) => void;
}

export const BlogPage: React.FC<BlogPageProps> = ({
  setActiveTab,
  selectedArticleId,
  onSelectArticle
}) => {
  const [articles, setArticles] = useState<BlogArticle[]>(INITIAL_BLOG_ARTICLES);
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');
  
  const [activeArticleModal, setActiveArticleModal] = useState<BlogArticle | null>(
    selectedArticleId ? articles.find(a => a.id === selectedArticleId) || null : null
  );

  // Auto-Article Generation State
  const [generating, setGenerating] = useState<boolean>(false);
  const [customTopicInput, setCustomTopicInput] = useState<string>('');
  const [genSuccessMessage, setGenSuccessMessage] = useState<string | null>(null);

  const categories = ['All', 'AI Development', 'UI/UX Design', 'Business Analytics', 'Tech Education', 'SEO Strategy'];

  const filteredArticles = articles.filter((art) => {
    const matchesCategory = selectedCategory === 'All' || art.category === selectedCategory;
    const matchesSearch = searchQuery === '' || 
      art.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
      art.excerpt.toLowerCase().includes(searchQuery.toLowerCase()) ||
      art.tags.some(t => t.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesCategory && matchesSearch;
  });

  const handleGenerateWeeklyArticle = async () => {
    setGenerating(true);
    setGenSuccessMessage(null);

    const topicToUse = customTopicInput.trim() || undefined;

    try {
      const response = await fetch('/api/blog/generate-article', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topicToUse,
          category: selectedCategory !== 'All' ? selectedCategory : 'AI Development'
        })
      });

      const data = await response.json();
      if (response.ok && data.article) {
        const newArt: BlogArticle = {
          ...data.article,
          isAutoGenerated: true
        };
        setArticles([newArt, ...articles]);
        setGenSuccessMessage(`New SEO Article Published: "${newArt.title}"`);
        setCustomTopicInput('');
        setTimeout(() => setGenSuccessMessage(null), 5000);
      }
    } catch (err) {
      console.error('Failed to generate weekly article:', err);
    } finally {
      setGenerating(false);
    }
  };

  const openArticleModal = (art: BlogArticle) => {
    setActiveArticleModal(art);
    if (onSelectArticle) onSelectArticle(art.id);
  };

  const closeArticleModal = () => {
    setActiveArticleModal(null);
    if (onSelectArticle) onSelectArticle(null);
  };

  return (
    <div className="space-y-16 pb-20">
      
      {/* Header */}
      <div className="text-center space-y-4 max-w-3xl mx-auto pt-6">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-slate-900 border border-blue-500/30 text-xs font-mono text-amber-400">
          <BookOpen className="w-4 h-4" />
          <span>SEO & Thought Leadership Engine</span>
        </div>
        <h1 className="font-heading text-4xl sm:text-5xl font-extrabold text-slate-100 tracking-tight">
          SEO Tech Blog & Client Insights
        </h1>
        <p className="text-slate-300 text-sm sm:text-base font-light leading-relaxed">
          Weekly technical insights on AI engineering, UI/UX design systems, business analytics, and tech education engineered to drive client acquisition.
        </p>
      </div>

      {/* Auto-Weekly Generation Control Panel */}
      <div className="max-w-5xl mx-auto px-4">
        <div className="p-6 sm:p-8 rounded-3xl bg-slate-900/90 border border-amber-500/40 space-y-4 soft-glow-mustard relative">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-400/40 flex items-center justify-center text-amber-300">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-heading font-bold text-slate-100 text-base">Weekly SEO Auto-Publish Engine</h3>
                <p className="text-xs text-slate-400 font-mono">Status: Active • Powered by Gemini AI</p>
              </div>
            </div>

            <span className="text-[10px] font-mono px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 flex items-center gap-1.5 self-start sm:self-auto">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              Auto-SEO Scheduler Active
            </span>
          </div>

          <p className="text-xs text-slate-300 font-light">
            Need a fresh SEO article for client acquisition right now? Enter a custom topic or trigger our automated weekly AI generator to publish a structured article with key takeaways.
          </p>

          {genSuccessMessage && (
            <div className="p-3 rounded-xl bg-emerald-950/80 border border-emerald-500/40 text-emerald-300 text-xs flex items-center gap-2 animate-in fade-in">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>{genSuccessMessage}</span>
            </div>
          )}

          <div className="flex flex-col sm:flex-row gap-3 pt-1">
            <input
              type="text"
              value={customTopicInput}
              onChange={(e) => setCustomTopicInput(e.target.value)}
              placeholder="e.g. Impact of AI Agents on Modern SaaS Conversion Funnels"
              className="flex-1 px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-100 text-xs focus:border-amber-400 focus:outline-none"
            />
            <button
              onClick={handleGenerateWeeklyArticle}
              disabled={generating}
              className="px-6 py-2.5 rounded-xl font-bold text-slate-950 bg-mustard-gradient hover:bg-mustard-hover transition-all text-xs flex items-center justify-center gap-2 shrink-0"
            >
              {generating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Generating Weekly Article...</span>
                </>
              ) : (
                <>
                  <Plus className="w-4 h-4" />
                  <span>Auto-Publish Weekly Article</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Category Pills & Search */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          
          {/* Categories */}
          <div className="flex flex-wrap items-center gap-2">
            {categories.map((cat) => {
              const isActive = selectedCategory === cat;
              return (
                <button
                  key={cat}
                  onClick={() => setSelectedCategory(cat)}
                  className={`px-3.5 py-1.5 rounded-full text-xs font-semibold transition-all ${
                    isActive
                      ? 'bg-mustard-gradient text-slate-950 soft-glow-mustard'
                      : 'bg-slate-900 text-slate-300 hover:text-white border border-slate-800'
                  }`}
                >
                  {cat}
                </button>
              );
            })}
          </div>

          {/* Search Bar */}
          <div className="relative w-full md:w-64">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search articles..."
              className="w-full pl-9 pr-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-100 text-xs focus:border-amber-400 focus:outline-none"
            />
          </div>

        </div>

        {/* Article Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredArticles.map((art) => (
            <div
              key={art.id}
              onClick={() => openArticleModal(art)}
              className="bg-blue-card p-6 sm:p-8 rounded-2xl cursor-pointer hover:border-amber-400/40 transition-all duration-300 space-y-4 flex flex-col justify-between soft-drop-shadow group"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between text-xs text-slate-400 font-mono">
                  <span className="px-2.5 py-1 rounded bg-blue-950 text-amber-300 border border-blue-800/40">
                    {art.category}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" />
                    {art.readTime}
                  </span>
                </div>

                <h3 className="font-heading text-xl font-bold text-slate-100 group-hover:text-amber-300 transition-colors">
                  {art.title}
                </h3>

                <p className="text-xs text-slate-300 leading-relaxed font-light line-clamp-3">
                  {art.excerpt}
                </p>
              </div>

              <div className="pt-4 border-t border-slate-800/80 space-y-3">
                {/* Key Takeaways snippet */}
                {art.keyTakeaways && art.keyTakeaways.length > 0 && (
                  <div className="p-3 rounded-xl bg-slate-950 border border-blue-900/40 text-[11px] text-slate-300 space-y-1">
                    <span className="text-[10px] font-mono text-amber-400 uppercase font-bold">Key Insight:</span>
                    <p className="line-clamp-2 italic font-light">"{art.keyTakeaways[0]}"</p>
                  </div>
                )}

                <div className="flex items-center justify-between text-xs text-amber-400 font-semibold pt-1">
                  <span>Read Article & Analysis</span>
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Article Detail Modal */}
      {activeArticleModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md animate-in fade-in">
          <div className="bg-slate-900 border border-amber-500/40 rounded-3xl max-w-3xl w-full max-h-[90vh] overflow-y-auto p-6 sm:p-10 space-y-6 soft-glow-mustard relative">
            
            <button
              onClick={closeArticleModal}
              className="absolute top-5 right-5 p-2 rounded-full bg-slate-800 text-slate-300 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="space-y-3 pr-8">
              <div className="flex items-center gap-2">
                <span className="px-3 py-1 rounded-full text-xs font-mono font-bold bg-amber-400/20 text-amber-300 border border-amber-400/30">
                  {activeArticleModal.category}
                </span>
                {activeArticleModal.isAutoGenerated && (
                  <span className="px-3 py-1 rounded-full text-xs font-mono font-bold bg-blue-500/20 text-blue-300 border border-blue-500/30">
                    Generated via Weekly Gemini Engine
                  </span>
                )}
              </div>

              <h2 className="font-heading text-2xl sm:text-4xl font-extrabold text-slate-100 leading-snug">
                {activeArticleModal.title}
              </h2>

              <div className="flex items-center gap-4 text-xs text-slate-400 font-mono">
                <span>By {activeArticleModal.author}</span>
                <span>•</span>
                <span>{activeArticleModal.publishedAt}</span>
                <span>•</span>
                <span>{activeArticleModal.readTime}</span>
              </div>
            </div>

            {/* Key Takeaways Box */}
            {activeArticleModal.keyTakeaways && activeArticleModal.keyTakeaways.length > 0 && (
              <div className="p-5 rounded-2xl bg-slate-950 border border-amber-500/30 space-y-2">
                <h4 className="text-xs font-mono uppercase font-bold text-amber-400 flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4" />
                  <span>Executive Key Takeaways</span>
                </h4>
                <ul className="space-y-1.5 text-xs text-slate-200">
                  {activeArticleModal.keyTakeaways.map((point, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                      <span className="font-light">{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Markdown / Content Text */}
            <div className="prose prose-invert max-w-none text-xs sm:text-sm text-slate-200 leading-relaxed space-y-4 font-light whitespace-pre-line">
              {activeArticleModal.content}
            </div>

            {/* Tags */}
            <div className="pt-4 border-t border-slate-800 flex flex-wrap gap-2">
              {activeArticleModal.tags.map((tag, i) => (
                <span key={i} className="px-3 py-1 rounded-lg text-[11px] font-mono bg-slate-950 text-blue-300 border border-blue-900/40">
                  #{tag}
                </span>
              ))}
            </div>

            {/* Lead Conversion Call to Action */}
            <div className="p-6 rounded-2xl bg-gradient-to-r from-blue-950 via-slate-900 to-slate-950 border border-amber-500/40 flex flex-col sm:flex-row items-center justify-between gap-4">
              <div>
                <h4 className="font-heading font-bold text-slate-100 text-sm">Need a Similar Solution for Your Company?</h4>
                <p className="text-xs text-slate-300 font-light">Schedule a 15-minute consultation with Solved by Tech engineers.</p>
              </div>
              <button
                onClick={() => {
                  closeArticleModal();
                  setActiveTab('services');
                  document.getElementById('contact-form')?.scrollIntoView({ behavior: 'smooth' });
                }}
                className="px-6 py-2.5 rounded-xl font-bold text-xs text-slate-950 bg-mustard-gradient hover:bg-mustard-hover transition-all shrink-0"
              >
                Book Technical Consultation
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
};
