export type PageTab = 'home' | 'services' | 'packages' | 'teen-workshop' | 'portfolio' | 'blog' | 'testimonials' | 'contact';

export interface CoreServiceItem {
  id: string;
  title: string;
  description: string;
  mainResult: string;
  iconName: string;
  category: string;
}

export interface ServicePackage {
  id: string;
  name: string;
  idealFor: string;
  description: string;
  features: string[];
  ctaText: string;
  ctaType: 'quote' | 'consultation';
  highlighted?: boolean;
}

export interface Project {
  id: string;
  title: string;
  client: string;
  industry: string;
  category: 'AI & Web Applications' | 'UI/UX Design' | 'SEO & Digital Visibility' | 'Business Analytics' | 'Teen Tech Workshop';
  description: string;
  longDescription: string;
  challenge: string;
  solution: string;
  results: string[];
  techStack: string[];
  imageUrl: string;
  featured?: boolean;
}

export interface Service {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  description: string;
  deliverables: string[];
  iconName: string;
  estimatedTimeline: string;
  idealFor: string;
}

export interface Testimonial {
  id: string;
  clientName: string;
  clientRole: string;
  company: string;
  industry: string;
  avatarUrl: string;
  rating: number;
  content: string;
  impactMetric: string;
  projectType: string;
  verified: boolean;
}

export interface WorkshopSession {
  id: string;
  month: 'April' | 'August' | 'December';
  year: number;
  dates: string;
  status: 'Open for Registration' | 'Upcoming' | 'Completed';
  spotsAvailable: number;
  location: string;
}

export interface BlogArticle {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  category: 'AI Development' | 'UI/UX Design' | 'Business Analytics' | 'Tech Education' | 'SEO Strategy';
  tags: string[];
  author: string;
  publishedAt: string;
  readTime: string;
  keyTakeaways: string[];
  isAutoGenerated?: boolean;
}

export interface WorkshopRegistration {
  registrationCode: string;
  studentName: string;
  gradeLevel: 'Junior High' | 'Senior High';
  parentName: string;
  parentEmail: string;
  parentPhone: string;
  holidaySession: string;
  trackPreference: string;
  registeredAt: string;
}
